[package]
name = "facet-openapi"
version = "0.1.0"
edition = "2024"

[dependencies]
facet = "0.1.0"
facet-derive = "0.1.12"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
